### ISSUE TITLE
Documentation update for CustomData.add_data

### ISSUE THREAD

**Issue by matchaxnb** [ambiguousname/jackbox-custom-content#10]
Hey,

Just wanted to let you know that for CustomData.add_data:

- t stands for type = type of the value, such as string (S), boolean (B), audio (A), ...
- v stands for value, that is the actual value
- n stands for name of the custom data field.
I'm going to study your project, I've made a smaller, quiplash-oriented python library that you may want to check out: https://github.com/matchaxnb/python-quiplash

Cheers
Matcha

**Comment by ambiguousname** [comment]
Thanks for letting me know!

I've updated JPPC.py with that info, and I'll keep it in mind with the updates I'm working on.

I also checked out the python library, I might reference it in the future if I ever go back and expand support to Quiplash 1 and 2.

Thank you again!
